# Generated by Django 2.2 on 2020-04-17 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('class_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_present', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['subject', 'class_date'],
            },
        ),
    ]
